### ISSUE TITLE
Change to event.Event.objects.filter and change parameter

### ISSUE THREAD

**Issue by matthewman** [alvinleung1996/tutoria-server#10]
https://github.com/alvinleung1996/tutoria-server/blob/4773028df3b330dfcb53a6a11b3ca1145dc09645/tutoriaapi/models/tutorial.py#L38

**Comment by alvinleung1996** [comment]
Basically the problem is not related to the filter, but to the fact that I forgot to check if the tutor himself has another event at the same time by calling `self.user.has_no_event(start_time, end_time)`. (Actually I called this in the student model class, but not in the tutor model class)
